# Dictionnaires de ressources linguistiques pour l'application Tolo Distribution

LANG_FR = {
    "app_title": "Gestion Tolo Distribution",
    "welcome_message": "Bienvenue dans le système de gestion Tolo Distribution - Rôle : {role}",
    "manage_products": "Gérer les Produits",
    "manage_sales": "Gérer les Ventes",
    "manage_clients": "Gérer les Clients",
    "manage_stock": "Gérer le Stock",
    "manage_suppliers": "Gérer les Fournisseurs",
    "manage_orders": "Gérer les Commandes",
    "manage_billing": "Facturation et Factures",
    "manage_reporting": "Rapports et Statistiques",
    "category_label": "Catégorie :",
    "reference_label": "Référence :",
    "purchase_price_label": "Prix d'achat :",
    "sale_price_label": "Prix de vente :",
    "stock_quantity_label": "Quantité en stock :",
    "add_product_btn": "Ajouter Produit",
    "update_product_btn": "Mettre à jour Produit",
    "delete_product_btn": "Supprimer Produit",
    "error_required_fields": "La catégorie et la référence sont obligatoires.",
    "success_product_added": "Produit ajouté avec succès.",
    "success_product_updated": "Produit mis à jour avec succès.",
    "success_product_deleted": "Produit supprimé avec succès.",
    "error": "Erreur",
    "success": "Succès",
    "select_language": "Choisir la langue",
    "language_french": "Français",
    "language_english": "Anglais",
    # Keys from sales_management.py
    "select_product_label": "Sélectionner le produit :",
    "available_stock_label": "Stock disponible :",
    "quantity_label": "Quantité :",
    "payment_method_label": "Mode de paiement :",
    "payment_cash": "Espèces",
    "payment_mobile_money": "Mobile Money",
    "payment_credit": "Crédit",
    "client_for_credit_label": "Client (pour crédit) :",
    "total_amount_label": "Montant total :",
    "record_sale_btn": "Enregistrer la vente",
    "clear_btn": "Effacer",
    "date_label": "Date",
    "product_label": "Produit",
    "client_label": "Client",
    "profit_label": "Profit",
    "error_select_valid_product": "Veuillez sélectionner un produit valide.",
    "error_quantity_positive": "La quantité doit être supérieure à zéro.",
    "error_insufficient_stock": "Stock insuffisant pour le produit sélectionné.",
    "error_client_not_found": "Client sélectionné introuvable.",
    "success_sale_recorded": "Vente enregistrée avec succès.",
    # Keys from product_management.py
    "category_electromenager": "Électroménager",
    "category_phones": "Téléphones",
    "category_accessories": "Accessoires",
    "category_misc": "Divers",
    # Keys for supplier_management.py
    "supplier_management_title": "Gestion des Fournisseurs",
    "name_label": "Nom :",
    "contact_info_label": "Informations de contact :",
    "add_supplier_btn": "Ajouter Fournisseur",
    "update_supplier_btn": "Mettre à jour Fournisseur",
    "delete_supplier_btn": "Supprimer Fournisseur",
    "success_supplier_added": "Fournisseur ajouté avec succès.",
    "success_supplier_updated": "Fournisseur mis à jour avec succès.",
    "success_supplier_deleted": "Fournisseur supprimé avec succès.",
    "error_name_required": "Le nom est obligatoire.",
    "error_failed_add_supplier": "Échec de l'ajout du fournisseur : {error}",
    "error_failed_update_supplier": "Échec de la mise à jour du fournisseur : {error}",
    "error_failed_delete_supplier": "Échec de la suppression du fournisseur : {error}",
    # Keys for order_management.py
    "order_management_title": "Gestion des Commandes",
    "select_client_label": "Sélectionner le client :",
    "order_details_label": "Détails de la commande :",
    "status_label": "Statut :",
    "add_order_btn": "Ajouter Commande",
    "update_order_btn": "Mettre à jour Commande",
    "delete_order_btn": "Supprimer Commande",
    "status_pending": "En attente",
    "status_in_progress": "En cours",
    "status_delivered": "Livré",
    "status_cancelled": "Annulé",
    "error_client_required": "Le client et les détails de la commande sont obligatoires.",
    "error_client_not_found": "Client sélectionné introuvable.",
    "success_order_added": "Commande ajoutée avec succès.",
    "success_order_updated": "Commande mise à jour avec succès.",
    "success_order_deleted": "Commande supprimée avec succès.",
    # Keys for billing_management.py
    "billing_management_title": "Facturation et Factures",
    "generate_invoice_btn": "Générer la facture PDF",
    "export_invoice_btn": "Exporter la facture en PDF",
    "error_select_sale": "Veuillez sélectionner une vente pour générer la facture.",
    "error_sale_not_found": "Vente introuvable.",
    "success_invoice_generated": "Facture PDF générée : {file}",
    "success_invoice_exported": "Facture PDF exportée : {file}",
    # Keys for reporting_management.py
    "reporting_management_title": "Rapports et Statistiques",
    "select_report_type_label": "Sélectionner le type de rapport :",
    "generate_report_btn": "Générer le rapport",
    "export_excel_btn": "Exporter vers Excel",
    "report_daily_sales": "Ventes quotidiennes",
    "report_weekly_sales": "Ventes hebdomadaires",
    "report_monthly_sales": "Ventes mensuelles",
    "report_yearly_sales": "Ventes annuelles",
    "report_best_sellers": "Meilleures ventes",
    "success_report_exported": "Rapport exporté vers {file}",
    # Keys for user_management.py
    "login_title": "Connexion - Tolo Distribution",
    "username_label": "Nom d'utilisateur :",
    "password_label": "Mot de passe :",
    "login_btn": "Connexion",
    "error_enter_credentials": "Veuillez entrer le nom d'utilisateur et le mot de passe.",
    "error_invalid_credentials": "Nom d'utilisateur ou mot de passe invalide.",
    # Keys for client_management.py
    "client_management_title": "Gestion des Clients",
    "name_label": "Nom :",
    "contact_number_label": "Numéro de contact :",
    "add_client_btn": "Ajouter Client",
    "update_client_btn": "Mettre à jour Client",
    "delete_client_btn": "Supprimer Client",
    "success_client_added": "Client ajouté avec succès.",
    "success_client_updated": "Client mis à jour avec succès.",
    "success_client_deleted": "Client supprimé avec succès.",
    "error_name_required": "Le nom est obligatoire.",
    "error_failed_add_client": "Échec de l'ajout du client : {error}",
    "error_failed_update_client": "Échec de la mise à jour du client : {error}",
    "error_failed_delete_client": "Échec de la suppression du client : {error}",
    # Keys for stock_management.py
    "stock_management_title": "Gestion du Stock",
    "select_product_label": "Sélectionner le produit :",
    "quantity_label": "Quantité :",
    "select_supplier_label": "Sélectionner le fournisseur :",
    "add_stock_entry_btn": "Ajouter une entrée de stock",
    "clear_btn": "Effacer",
    "error_select_product_quantity": "Veuillez sélectionner un produit et entrer une quantité valide.",
    "error_product_not_found": "Produit sélectionné introuvable.",
    "success_stock_entry_added": "Entrée de stock ajoutée avec succès.",
}

LANG_EN = {
    "app_title": "Tolo Distribution Management",
    "welcome_message": "Welcome to Tolo Distribution Management System - Role: {role}",
    "manage_products": "Manage Products",
    "manage_sales": "Manage Sales",
    "manage_clients": "Manage Clients",
    "manage_stock": "Manage Stock",
    "manage_suppliers": "Manage Suppliers",
    "manage_orders": "Manage Orders",
    "manage_billing": "Billing & Invoicing",
    "manage_reporting": "Reporting & Statistics",
    "category_label": "Category:",
    "reference_label": "Reference:",
    "purchase_price_label": "Purchase Price:",
    "sale_price_label": "Sale Price:",
    "stock_quantity_label": "Stock Quantity:",
    "add_product_btn": "Add Product",
    "update_product_btn": "Update Product",
    "delete_product_btn": "Delete Product",
    "error_required_fields": "Category and Reference are required.",
    "success_product_added": "Product added successfully.",
    "success_product_updated": "Product updated successfully.",
    "success_product_deleted": "Product deleted successfully.",
    "error": "Error",
    "success": "Success",
    "select_language": "Select Language",
    "language_french": "French",
    "language_english": "English",
    # Keys from sales_management.py
    "select_product_label": "Select Product:",
    "available_stock_label": "Available Stock:",
    "quantity_label": "Quantity:",
    "payment_method_label": "Payment Method:",
    "payment_cash": "Cash",
    "payment_mobile_money": "Mobile Money",
    "payment_credit": "Credit",
    "client_for_credit_label": "Client (for credit):",
    "total_amount_label": "Total Amount:",
    "record_sale_btn": "Record Sale",
    "clear_btn": "Clear",
    "date_label": "Date",
    "product_label": "Product",
    "client_label": "Client",
    "profit_label": "Profit",
    "error_select_valid_product": "Please select a valid product.",
    "error_quantity_positive": "Quantity must be greater than zero.",
    "error_insufficient_stock": "Insufficient stock for the selected product.",
    "error_client_not_found": "Selected client not found.",
    "success_sale_recorded": "Sale recorded successfully.",
    # Keys from product_management.py
    "category_electromenager": "Electroménager",
    "category_phones": "Phones",
    "category_accessories": "Accessories",
    "category_misc": "Misc",
    # Keys for supplier_management.py
    "supplier_management_title": "Supplier Management",
    "name_label": "Name:",
    "contact_info_label": "Contact Info:",
    "add_supplier_btn": "Add Supplier",
    "update_supplier_btn": "Update Supplier",
    "delete_supplier_btn": "Delete Supplier",
    "success_supplier_added": "Supplier added successfully.",
    "success_supplier_updated": "Supplier updated successfully.",
    "success_supplier_deleted": "Supplier deleted successfully.",
    "error_name_required": "Name is required.",
    "error_failed_add_supplier": "Failed to add supplier: {error}",
    "error_failed_update_supplier": "Failed to update supplier: {error}",
    "error_failed_delete_supplier": "Failed to delete supplier: {error}",
    # Keys for order_management.py
    "order_management_title": "Order Management",
    "select_client_label": "Select Client:",
    "order_details_label": "Order Details:",
    "status_label": "Status:",
    "add_order_btn": "Add Order",
    "update_order_btn": "Update Order",
    "delete_order_btn": "Delete Order",
    "status_pending": "Pending",
    "status_in_progress": "In Progress",
    "status_delivered": "Delivered",
    "status_cancelled": "Cancelled",
    "error_client_required": "Client and order details are required.",
    "error_client_not_found": "Selected client not found.",
    "success_order_added": "Order added successfully.",
    "success_order_updated": "Order updated successfully.",
    "success_order_deleted": "Order deleted successfully.",
    # Keys for billing_management.py
    "billing_management_title": "Billing and Invoicing",
    "generate_invoice_btn": "Generate Invoice PDF",
    "export_invoice_btn": "Export Invoice as PDF",
    "error_select_sale": "Please select a sale to generate invoice.",
    "error_sale_not_found": "Sale not found.",
    "success_invoice_generated": "Invoice PDF generated: {file}",
    "success_invoice_exported": "Invoice PDF exported: {file}",
    # Keys for reporting_management.py
    "reporting_management_title": "Reporting and Statistics",
    "select_report_type_label": "Select Report Type:",
    "generate_report_btn": "Generate Report",
    "export_excel_btn": "Export to Excel",
    "report_daily_sales": "Daily Sales",
    "report_weekly_sales": "Weekly Sales",
    "report_monthly_sales": "Monthly Sales",
    "report_yearly_sales": "Yearly Sales",
    "report_best_sellers": "Best Sellers",
    "success_report_exported": "Report exported to {file}",
    # Keys for user_management.py
    "login_title": "Login - Tolo Distribution",
    "username_label": "Username:",
    "password_label": "Password:",
    "login_btn": "Login",
    "error_enter_credentials": "Please enter username and password.",
    "error_invalid_credentials": "Invalid username or password.",
    # Keys for client_management.py
    "client_management_title": "Client Management",
    "name_label": "Name:",
    "contact_number_label": "Contact Number:",
    "add_client_btn": "Add Client",
    "update_client_btn": "Update Client",
    "delete_client_btn": "Delete Client",
    "success_client_added": "Client added successfully.",
    "success_client_updated": "Client updated successfully.",
    "success_client_deleted": "Client deleted successfully.",
    "error_name_required": "Name is required.",
    "error_failed_add_client": "Failed to add client: {error}",
    "error_failed_update_client": "Failed to update client: {error}",
    "error_failed_delete_client": "Failed to delete client: {error}",
    # Keys for stock_management.py
    "stock_management_title": "Stock Management",
    "select_product_label": "Select Product:",
    "quantity_label": "Quantity:",
    "select_supplier_label": "Select Supplier:",
    "add_stock_entry_btn": "Add Stock Entry",
    "clear_btn": "Clear",
    "error_select_product_quantity": "Please select a product and enter a valid quantity.",
    "error_product_not_found": "Selected product not found.",
    "success_stock_entry_added": "Stock entry added successfully.",
}
